#!/usr/bin/env bash

[[ -z $1 ]] && echo "Usage: vim-bash-script [-g] filename"
[[ $1 == "-g" ]] && file=~/.bin/$2 || file=$1

echo "#!/usr/bin/env bash" >> $file
echo "set -e" >> $file
chmod +x $file
vim $file

