#!/usr/bin/env bash

if [[ $1 ]]; then
    file=$(fzf +m -f "$1" | head -1)
else
    file=$(fzf +m)
fi

dir=$(dirname "$file")

# NOTE: For cd to work correctly, we need to source this file rather than execute it directly
# fzf-cd in ~/.aliases sources this file
cd "$dir"
