#!/usr/bin/env bash

[[ $1 ]] && file="$1" || exit
[[ $2 ]] && output="$2" || output="out.png"

data=`identify $file | awk '{print $3}'`
width=`echo $data | sed 's/[^0-9]/ /g' | awk '{print $1}'`
height=`echo $data | sed 's/[^0-9]/ /g' | awk '{print $2}'`
new_width=$((width/2))
new_height=$((height/2))

convert -verbose -crop ${width}x${new_height} $file $output

# This doesn't seem necessary? The prior one already produces top+bottom
#convert -verbose -crop ${width}x${height}+${new_width}-0 $file $output2 # make right half
