#!/usr/bin/env bash

if [[ -z $1 ]]; then
    echo "Usage: xctest [scheme] [target]"
    exit
fi

workspace="Pixelist.xcworkspace"
scheme="$1"

simulator="platform=iOS Simulator,name=iPhone 8"

xcodebuild \
    build-for-testing \
    -workspace "$workspace" \
    -scheme "$scheme" \
    -destination "$simulator" \
    -configuration Debug | tee ~/.testOutput.txt

xcodebuild \
    test-without-building \
    -workspace "$workspace" \
    -scheme "$scheme" \
    -destination "$simulator" \
    -configuration Debug | tee ~/.testOutput.txt

#    -target "$target" \
#    -scheme "$scheme" \
#    -target "$target" \

