#!/usr/bin/env bash
set -e

[[ $1 == "--lucky" ]] && query="$2" || query="$1"

encodedQuery=$(echo "$query" | sed -e "s/ /+/g")

if [[ $1 == "--lucky" ]]; then
    lynx "https://duckduckgo.com/?q=!+${encodedQuery}"
else
    lynx "https://duckduckgo.com/?q=${encodedQuery}"
fi
